INSERT INTO show (
  trakt_id, 
  title, 
  slug, 
  imdb_id, 
  year, 
  overview, 
  network, 
  updated_at, 
  aired_episodes, 
  status,
  tmdb_id,
  tmdb_image_path
  )
VALUES
    (60842, 
    'Please Like Me', 
    'please-like-me', 
    'tt2155025', 
    2013, 
    'After breaking up with his girlfriend, Josh comes to the realization that he is homosexual. With the support of his now ex girlfriend Claire, and his best friend and house mate Tom, Josh must help his mother with her battle with depression and the rest of his family embrace his new found orientation.',
    'ABC Comedy',
    '2020-10-09T08:46:34.000Z',
    32,
    'ended',
    61350,
    '/dgzpboEMxpHVI3Isy5lZOCP2e6X.jpg'
    ),
    (145026, 
    'Watchmen', 
    'watchmen', 
    'tt7049682', 
    2019, 
    'A modern-day reimagining where superheroes are treated as outlaws and must embrace the nostalgia.',
    'HBO',
    '2020-09-29T17:40:00.000Z',
    9,
    'ended',
    79788,
    '/m8rWq3j73ZGhDuSCZWMMoE9ePH1.jpg'
    ),
    (123775, 
    'Dark', 
    'dark', 
    'tt5753856', 
    2017, 
    'When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids. The mystery-drama series introduces an intricate puzzle filled with twists that includes a web of curious characters, all of whom have a connection to the town''s troubled history -- whether they know it or not. The story includes supernatural elements that tie back to the same town in 1986.',
    'Netflix',
    '2020-11-11T18:36:44.000Z',
    26,
    'ended',
    70523,
    '/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg'
    ),
    (134752, 
    'The Masked Singer', 
    'the-masked-singer', 
    'tt7670568', 
    2019, 
    'A top-secret singing competition in which celebrities face off against each other and appear in elaborate costumes with full facemasks to conceal their identities. American version of the popular Korean game show ''King of Mask Singer''.',
    'FOX',
    '2020-10-31T09:30:09.000Z',
    47,
    'returning series',
    84910,
    '/y90vIG3LY7okHfF444hK1IgHnvg.jpg'
    ),
    (913, 
    'M*A*S*H', 
    'm-a-s-h', 
    'tt0068098', 
    1972, 
    'The 4077th Mobile Army Surgical Hospital is stuck in the middle of the Korean war. With little help from the circumstances they find themselves in, they are forced to make their own fun. Fond of practical jokes and revenge, the doctors, nurses, administrators, and soldiers often find ways of making wartime life bearable.',
    'CBS',
    '2020-10-13T09:06:36.000Z',
    251,
    'ended',
    918,
    '/6rhuM3oMoEWKxAdrm7IyM8oq8cC.jpg'
    ),
    (245, 
    'Avatar: The Last Airbender', 
    'avatar-the-last-airbender', 
    'tt0417299', 
    2005, 
    'With the Fire Nation on the brink of global domination, a young boy reawakens after a hundred-year absence. To save his war-torn world he must accept his destiny as the Avatar before it''s too late.',
    'Nickelodeon',
    '2020-11-11T09:17:38.000Z',
    61,
    'ended',
    246,
    '/cHFZA8Tlv03nKTGXhLOYOLtqoSm.jpg'
    );
  